# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transactions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transactions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12transactions.proto\x12\x0ctransactions\"\xec\x01\n\x0bTransaction\x12\x15\n\rTransactionID\x18\x01 \x01(\t\x12\x16\n\x0eTransactionAmt\x18\x02 \x01(\x01\x12\x0f\n\x07isFraud\x18\x03 \x01(\x05\x12\r\n\x05\x63\x61rd1\x18\x04 \x01(\x05\x12\r\n\x05\x61\x64\x64r1\x18\x05 \x01(\x05\x12\r\n\x05\x61\x64\x64r2\x18\x06 \x01(\x05\x12\x12\n\nDeviceType\x18\x07 \x01(\t\x12\x15\n\rTransactionDT\x18\x08 \x01(\x03\x12\x10\n\x08\x63urrency\x18\t \x01(\t\x12\x19\n\x11merchant_category\x18\n \x01(\t\x12\x18\n\x10\x61\x63\x63ount_age_days\x18\x0b \x01(\x05\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x12TransactionService\x12\x44\n\x12StreamTransactions\x12\x19.transactions.Transaction\x1a\x11.transactions.Ack(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=37
  _globals['_TRANSACTION']._serialized_end=273
  _globals['_ACK']._serialized_start=275
  _globals['_ACK']._serialized_end=297
  _globals['_TRANSACTIONSERVICE']._serialized_start=299
  _globals['_TRANSACTIONSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
